import type { Rule } from "./models";

export const RULES: Rule[] = [
  {
    code: "OWNER_IDENTITY_MISMATCH",
    name: "Owner identity mismatch",
    jurisdiction: "ANY",
    category: "IDENTITY",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "OWNER_IDENTITY_MISMATCH",
    minimumConfidence: 0.9,
    scoreImpact: -20,
    scoreCap: 55,
    recommendation: "Reconcile the owner name and identity number across the current land record, transfer instrument and identity document.",
    legalSources: ["PD-LAW-PLRA-2017", "PD-LAW-LRA-1967"],
    enabled: true
  },
  {
    code: "ACTIVE_MORTGAGE_PRESENT",
    name: "Active mortgage recorded",
    jurisdiction: "ANY",
    category: "ENCUMBRANCE",
    severity: "CRITICAL",
    effect: "BLOCKER",
    observationCode: "ACTIVE_MORTGAGE_PRESENT",
    minimumConfidence: 0.85,
    scoreImpact: -35,
    scoreCap: 45,
    recommendation: "Do not complete the purchase until verified redemption and an updated clear land record are supplied.",
    legalSources: ["PD-LAW-TPA-1882"],
    enabled: true
  },
  {
    code: "ACTIVE_COURT_LIEN_PRESENT",
    name: "Court lien or transfer restriction",
    jurisdiction: "ANY",
    category: "ENCUMBRANCE",
    severity: "CRITICAL",
    effect: "BLOCKER",
    observationCode: "ACTIVE_COURT_LIEN_PRESENT",
    minimumConfidence: 0.85,
    scoreImpact: -45,
    scoreCap: 35,
    recommendation: "Obtain a court discharge order and a fresh revenue record before any transfer.",
    legalSources: ["PD-LAW-LRA-1967"],
    enabled: true
  },
  {
    code: "MUTATION_NOT_RECONCILED_WITH_CURRENT_RECORD",
    name: "Mutation not reconciled with current ownership record",
    jurisdiction: "PUNJAB",
    category: "OWNERSHIP",
    severity: "HIGH",
    effect: "INCONCLUSIVE",
    observationCode: "MUTATION_NOT_RECONCILED_WITH_CURRENT_RECORD",
    minimumConfidence: 0.75,
    scoreImpact: -15,
    recommendation: "Obtain a fresh dated Fard or Jamabandi after the mutation and reconcile the transferred area and shares.",
    legalSources: ["PD-LAW-LRA-1967", "PD-LAW-LRR-1968", "PD-LAW-PLRA-2017"],
    enabled: true
  },
  {
    code: "POA_SCOPE_EXCEEDED",
    name: "Attorney authority may exceed principal interest",
    jurisdiction: "ANY",
    category: "AUTHORITY",
    severity: "CRITICAL",
    effect: "BLOCKER",
    observationCode: "POA_SCOPE_EXCEEDED",
    minimumConfidence: 0.85,
    scoreImpact: -40,
    scoreCap: 30,
    recommendation: "Verify the principal's current share and limit the transaction to the express scope of the registered Power of Attorney.",
    legalSources: ["PD-LAW-TPA-1882", "PD-SERVICE-MOFA-2026"],
    enabled: true
  },
  {
    code: "APPLICATION_NOT_APPROVAL",
    name: "Application uploaded without approval evidence",
    jurisdiction: "ANY",
    category: "COMPLETENESS",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "APPLICATION_NOT_APPROVAL",
    minimumConfidence: 0.8,
    scoreImpact: -10,
    recommendation: "Supply the authority's admitted, approved or updated transfer record; an application alone does not prove transfer.",
    legalSources: [],
    enabled: true
  },
  {
    code: "UNEXECUTED_TEMPLATE",
    name: "Unexecuted template detected",
    jurisdiction: "ANY",
    category: "COMPLETENESS",
    severity: "HIGH",
    effect: "INCONCLUSIVE",
    observationCode: "UNEXECUTED_TEMPLATE",
    minimumConfidence: 0.85,
    scoreImpact: -20,
    recommendation: "Upload the completed, signed and registered instrument instead of a blank template.",
    legalSources: [],
    enabled: true
  },
  {
    code: "NEC_SEARCH_PERIOD_STALE",
    name: "Non-encumbrance search period is stale",
    jurisdiction: "ANY",
    category: "ENCUMBRANCE",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "NEC_SEARCH_PERIOD_STALE",
    minimumConfidence: 0.8,
    scoreImpact: -8,
    recommendation: "Obtain a fresh non-encumbrance search covering the period up to the proposed completion date.",
    legalSources: [],
    enabled: true
  },
  {
    code: "OUT_OF_JURISDICTION",
    name: "Document is outside Pakistan jurisdiction",
    jurisdiction: "FOREIGN",
    category: "JURISDICTION",
    severity: "HIGH",
    effect: "INFORMATION",
    observationCode: "OUT_OF_JURISDICTION",
    minimumConfidence: 0.9,
    scoreImpact: 0,
    recommendation: "Exclude this document from the Pakistan property assessment and seek jurisdiction-specific advice.",
    legalSources: [],
    enabled: true
  },
  {
    code: "CRITICAL_DOCUMENT_UNREADABLE",
    name: "Critical title document unreadable",
    jurisdiction: "ANY",
    category: "COMPLETENESS",
    severity: "CRITICAL",
    effect: "INCONCLUSIVE",
    observationCode: "CRITICAL_DOCUMENT_UNREADABLE",
    minimumConfidence: 0.7,
    scoreImpact: -25,
    recommendation: "Upload a clearer scan or certified copy before relying on the report.",
    legalSources: [],
    enabled: true
  }
,
  {
    code: "LANDLORD_NOT_ON_TITLE",
    name: "Landlord not matching ownership record",
    jurisdiction: "ANY",
    category: "AUTHORITY",
    severity: "CRITICAL",
    effect: "BLOCKER",
    observationCode: "LANDLORD_NOT_ON_TITLE",
    minimumConfidence: 0.8,
    scoreImpact: -40,
    scoreCap: 35,
    recommendation: "Do not pay rent or deposit until the landlord's name is reconciled with a current Fard, society title or allotment record.",
    legalSources: ["PD-LAW-TPA-1882"],
    enabled: true
  },
  {
    code: "LEASE_TERM_INCONSISTENT",
    name: "Lease term or rent figures inconsistent",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "LEASE_TERM_INCONSISTENT",
    minimumConfidence: 0.75,
    scoreImpact: -12,
    recommendation: "Reconcile term dates and consideration amounts across all pages of the tenancy or lease instrument.",
    legalSources: ["PD-LAW-TPA-1882"],
    enabled: true
  },
  {
    code: "LEASE_STAMP_OR_REGISTRATION_CUES_MISSING",
    name: "Lease stamp or registration cues missing",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "LEASE_STAMP_OR_REGISTRATION_CUES_MISSING",
    minimumConfidence: 0.7,
    scoreImpact: -18,
    scoreCap: 60,
    recommendation: "Confirm stamp duty and registration requirements for the instrument class in the relevant province before relying on the lease.",
    legalSources: ["PD-LAW-STAMP-1899"],
    enabled: true
  }

,
  {
    code: "ALLOTMENT_NOC_BENEFICIARY_MISMATCH",
    name: "Allotment vs NOC beneficiary mismatch",
    jurisdiction: "ANY",
    category: "IDENTITY",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "ALLOTMENT_NOC_BENEFICIARY_MISMATCH",
    minimumConfidence: 0.8,
    scoreImpact: -22,
    scoreCap: 50,
    recommendation: "Reconcile the allotment letter holder with the society NOC beneficiary before transfer funds are released.",
    legalSources: [],
    enabled: true
  },
  {
    code: "SOCIETY_NDC_DUES_OUTSTANDING",
    name: "Society NDC shows outstanding dues",
    jurisdiction: "ANY",
    category: "ENCUMBRANCE",
    severity: "HIGH",
    effect: "DEDUCTION",
    observationCode: "SOCIETY_NDC_DUES_OUTSTANDING",
    minimumConfidence: 0.75,
    scoreImpact: -15,
    recommendation: "Clear documented society dues and obtain an updated NDC before completing transfer.",
    legalSources: [],
    enabled: true
  }

,
  {
    code: "MISSING_UPDATED_FARD",
    name: "Current ownership record missing after transfer",
    jurisdiction: "ANY",
    category: "COMPLETENESS",
    severity: "HIGH",
    effect: "INCONCLUSIVE",
    observationCode: "MISSING_UPDATED_FARD",
    minimumConfidence: 0.9,
    scoreImpact: -18,
    recommendation: "Obtain a fresh dated Fard or Jamabandi showing the position after the transfer mutation.",
    legalSources: ["PD-LAW-LRA-1967", "PD-LAW-PLRA-2017"],
    enabled: true
  }

,
  {
    code: "DEED_WITHOUT_MUTATION_EVIDENCE",
    name: "Registered deed without mutation evidence",
    jurisdiction: "ANY",
    category: "OWNERSHIP",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "DEED_WITHOUT_MUTATION_EVIDENCE",
    minimumConfidence: 0.9,
    scoreImpact: -25,
    scoreCap: 55,
    recommendation: "Obtain Inteqal / mutation proof on the revenue record before treating the registered deed as fully reflected in ownership.",
    legalSources: ["PD-LAW-LRA-1967", "PD-LAW-PLRA-2017"],
    enabled: true
  }

,
  {
    code: "TENANCY_NOT_IN_WRITING",
    name: "Tenancy not reduced to writing",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "TENANCY_NOT_IN_WRITING",
    minimumConfidence: 0.85,
    scoreImpact: -20,
    scoreCap: 50,
    recommendation: "Obtain a written tenancy agreement identifying parties, premises, term, rent and deposit. Provincial law generally expects writing; this is decision-support, not a validity ruling.",
    legalSources: ["PD-LAW-PRPA-2009"],
    enabled: true
  },
  {
    code: "TENANCY_REGISTRATION_CUES_ABSENT",
    name: "Tenancy registration / Rent Registrar cues absent",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "TENANCY_REGISTRATION_CUES_ABSENT",
    minimumConfidence: 0.75,
    scoreImpact: -12,
    recommendation: "Check whether the tenancy must be presented to the Rent Registrar/controller and/or registered under the Registration Act for the term involved in this province.",
    legalSources: ["PD-LAW-PRPA-2009", "PD-LAW-REG-1908"],
    enabled: true
  },
  {
    code: "SECURITY_DEPOSIT_UNDOCUMENTED",
    name: "Security deposit not clearly documented",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "SECURITY_DEPOSIT_UNDOCUMENTED",
    minimumConfidence: 0.7,
    scoreImpact: -8,
    recommendation: "Document advance rent and security deposit amount and return conditions in the written agreement before large payments.",
    legalSources: ["PD-LAW-PRPA-2009"],
    enabled: true
  }

,
  {
    code: "TENANCY_REGISTRATION_CUES_ABSENT_PUNJAB",
    name: "Punjab: Rent Registrar / registration cues absent",
    jurisdiction: "PUNJAB",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "TENANCY_REGISTRATION_CUES_ABSENT",
    minimumConfidence: 0.75,
    scoreImpact: -14,
    recommendation: "Under the Punjab Rented Premises Act, 2009 framework, check presentation/entry of the tenancy with the Rent Registrar and whether Registration Act formalities apply to the term. Decision-support only.",
    legalSources: ["PD-LAW-PRPA-2009", "PD-LAW-REG-1908"],
    enabled: true
  },
  {
    code: "TENANCY_REGISTRATION_CUES_ABSENT_SINDH",
    name: "Sindh: tenancy stamp/registration cues absent",
    jurisdiction: "SINDH",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "TENANCY_REGISTRATION_CUES_ABSENT",
    minimumConfidence: 0.75,
    scoreImpact: -14,
    recommendation: "Under Sindh rented-premises practice (SRPO 1979 framework), verify written agreement, applicable stamp duty, and registration where required for the lease term. Decision-support only.",
    legalSources: ["PD-LAW-SRPO-1979", "PD-LAW-STAMP-1899"],
    enabled: true
  },
  {
    code: "TENANCY_REGISTRATION_CUES_ABSENT_ICT",
    name: "ICT: rent controller registration cues absent",
    jurisdiction: "ISLAMABAD_CDA",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "TENANCY_REGISTRATION_CUES_ABSENT",
    minimumConfidence: 0.75,
    scoreImpact: -14,
    recommendation: "For Islamabad, verify current ICT rent-controller registration/presentation requirements for the written tenancy. Decision-support only.",
    legalSources: ["PD-LAW-ICT-RENT"],
    enabled: true
  },
  {
    code: "TENANCY_REGISTRATION_CUES_ABSENT_KP",
    name: "KP: local rent registration cues absent",
    jurisdiction: "KHYBER_PAKHTUNKHWA",
    category: "DOCUMENT_INTEGRITY",
    severity: "MEDIUM",
    effect: "DEDUCTION",
    observationCode: "TENANCY_REGISTRATION_CUES_ABSENT",
    minimumConfidence: 0.75,
    scoreImpact: -12,
    recommendation: "Verify Khyber Pakhtunkhwa rented-premises / rent-controller formalities for written tenancies. Decision-support only.",
    legalSources: ["PD-LAW-KP-RENT"],
    enabled: true
  }

,
  {
    code: "AGREEMENT_TO_SELL_ONLY",
    name: "Agreement to sell without registered conveyance",
    jurisdiction: "ANY",
    category: "DOCUMENT_INTEGRITY",
    severity: "HIGH",
    effect: "SCORE_CAP",
    observationCode: "AGREEMENT_TO_SELL_ONLY",
    minimumConfidence: 0.8,
    scoreImpact: -25,
    scoreCap: 55,
    recommendation:
      "An agreement to sell / bayana is not a registered sale deed. Obtain the registered conveyance and match it to mutation before treating ownership as transferred.",
    legalSources: ["PD-LAW-TPA-1882", "PD-LAW-REG-1908"],
    enabled: true
  },
  {
    code: "SELLER_NOT_ON_CURRENT_TITLE",
    name: "Seller not on current title record",
    jurisdiction: "ANY",
    category: "OWNERSHIP",
    severity: "CRITICAL",
    effect: "BLOCKER",
    observationCode: "SELLER_NOT_ON_CURRENT_TITLE",
    minimumConfidence: 0.85,
    scoreImpact: -45,
    scoreCap: 30,
    recommendation:
      "Do not pay bayana or balance until the transferor is reconciled to the current Fard, allotment or society title record.",
    legalSources: ["PD-LAW-TPA-1882", "PD-LAW-LRA-1967"],
    enabled: true
  }

];
